/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5x8XRdZhIfU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Toggle } from "./ui/toggle";
import { Slider } from "./ui/slider";
import { Button } from "./ui/button";

export function LightSwitch() {
	return (
		<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 p-6">
			<div className="bg-white rounded-lg shadow-md dark:bg-gray-900 dark:text-gray-200">
				<div className="p-4">
					<div className="flex justify-between items-center mb-4">
						<h3 className="text-lg font-medium">Item 1</h3>
						<Toggle aria-label="Toggle item 1" />
					</div>
					<div className="flex items-center gap-4">
						<Slider defaultValue={[50]} max={100} step={10} />
						<div className="flex gap-2">
							<Button size="sm" variant="outline">
								10
							</Button>
							<Button size="sm" variant="outline">
								25
							</Button>
							<Button size="sm" variant="outline">
								50
							</Button>
							<Button size="sm" variant="outline">
								75
							</Button>
							<Button size="sm" variant="outline">
								100
							</Button>
						</div>
					</div>
				</div>
			</div>
			<div className="bg-white rounded-lg shadow-md dark:bg-gray-900 dark:text-gray-200">
				<div className="p-4">
					<div className="flex justify-between items-center mb-4">
						<h3 className="text-lg font-medium">Item 2</h3>
						<Toggle aria-label="Toggle item 2" />
					</div>
					<div className="flex items-center gap-4">
						<Slider defaultValue={[25]} max={100} step={10} />
						<div className="flex gap-2">
							<Button size="sm" variant="outline">
								10
							</Button>
							<Button size="sm" variant="outline">
								25
							</Button>
							<Button size="sm" variant="outline">
								50
							</Button>
							<Button size="sm" variant="outline">
								75
							</Button>
							<Button size="sm" variant="outline">
								100
							</Button>
						</div>
					</div>
				</div>
			</div>
			<div className="bg-white rounded-lg shadow-md dark:bg-gray-900 dark:text-gray-200">
				<div className="p-4">
					<div className="flex justify-between items-center mb-4">
						<h3 className="text-lg font-medium">Item 3</h3>
						<Toggle aria-label="Toggle item 3" />
					</div>
					<div className="flex items-center gap-4">
						<Slider defaultValue={[75]} max={100} step={10} />
						<div className="flex gap-2">
							<Button size="sm" variant="outline">
								10
							</Button>
							<Button size="sm" variant="outline">
								25
							</Button>
							<Button size="sm" variant="outline">
								50
							</Button>
							<Button size="sm" variant="outline">
								75
							</Button>
							<Button size="sm" variant="outline">
								100
							</Button>
						</div>
					</div>
				</div>
			</div>
			<div className="bg-white rounded-lg shadow-md dark:bg-gray-900 dark:text-gray-200">
				<div className="p-4">
					<div className="flex justify-between items-center mb-4">
						<h3 className="text-lg font-medium">Item 4</h3>
						<Toggle aria-label="Toggle item 4" />
					</div>
					<div className="flex items-center gap-4">
						<Slider defaultValue={[90]} max={100} step={10} />
						<div className="flex gap-2">
							<Button size="sm" variant="outline">
								10
							</Button>
							<Button size="sm" variant="outline">
								25
							</Button>
							<Button size="sm" variant="outline">
								50
							</Button>
							<Button size="sm" variant="outline">
								75
							</Button>
							<Button size="sm" variant="outline">
								100
							</Button>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
